# Generated by Django 4.0.5 on 2022-06-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_telegramuser_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='weight',
            field=models.FloatField(default=50),
        ),
    ]
