# Generated by Django 4.0.5 on 2022-06-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_telegramuser_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='height',
            field=models.FloatField(default=70),
        ),
    ]
