# Generated by Django 4.0.5 on 2022-06-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_telegramuser_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MkExersise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='weight',
            field=models.FloatField(default=50, max_length=3),
        ),
    ]
