# Generated by Django 4.0.5 on 2022-06-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_category_exercise_name_exercise_category'),
        ('user', '0007_mkexersise_alter_telegramuser_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaximExersise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.telegramuser')),
            ],
        ),
        migrations.DeleteModel(
            name='MkExersise',
        ),
    ]
