# Generated by Django 4.0.5 on 2022-06-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_maximexersise_delete_mkexersise'),
    ]

    operations = [
        migrations.AddField(
            model_name='maximexersise',
            name='maxim',
            field=models.FloatField(default=150),
        ),
    ]
