# Generated by Django 4.0.5 on 2022-06-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_maximexersise_maxim'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='bench_presss',
            field=models.FloatField(default=80),
        ),
    ]
