# Generated by Django 4.0.5 on 2022-06-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_telegramuser_bench_presss'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='dumbell_press',
            field=models.FloatField(default=80),
        ),
    ]
