# Generated by Django 4.0.5 on 2022-06-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_telegramuser_army_presss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='Army_presss',
            new_name='army_presss',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='Dumbell_prees_stayted',
            new_name='dumbell_prees_stayted',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='Giri',
            new_name='giri',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='Leg_press',
            new_name='leg_press',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='Otvedenie',
            new_name='otvedenie',
        ),
    ]
