# Generated by Django 4.0.5 on 2022-07-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_army_presss_telegramuser_army_presss_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaximExersise',
        ),
    ]
