# Generated by Django 4.0.5 on 2022-07-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_delete_maximexersise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='Pronation',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='army_presss',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='bars',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='bench_presss',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='biceps_seet',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='biceps_stay',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='block_arm',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='block_pull',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='dead_lifting_finger',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='dumbell_prees_stayted',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='dumbell_press',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='elastic',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='giri',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='leg_press',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='luchevaya',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='otvedenie',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='twisting_rod',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='ugal_biceps',
        ),
    ]
