# Generated by Django 4.0.5 on 2022-06-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_category_exercise_name_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
