# Generated by Django 4.0.5 on 2022-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_alter_exercise_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='maxim',
            field=models.FloatField(default=50),
        ),
    ]
