# Generated by Django 4.0.5 on 2022-06-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exercise_maxim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='maxim',
        ),
    ]
