# Generated by Django 4.0.5 on 2022-07-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_maximexersise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='formula',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
