# Generated by Django 4.0.6 on 2022-07-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_telegramuser_pronation_and_more'),
        ('exercise', '0009_rename_maximexersise_maximexercise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maximexercise',
            unique_together={('user', 'exercise')},
        ),
    ]
