# Generated by Django 4.0.6 on 2022-07-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_alter_maximexercise_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
