# Generated by Django 4.0.6 on 2022-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_exercise_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maximexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='maximexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
