# Generated by Django 4.0.6 on 2022-07-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_alter_exercise_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='tutorial',
        ),
    ]
